version: "3.8"

services:
  scan-worker:
    image: scanii/scan-worker
    build:
      context: ../apps/scan-worker
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    volumes:
      - ../apps/scan-worker:/app
    working_dir: /app
    command: npm run dev
    depends_on:
      - result-api
      - upload-api
  result-api:
    image: scanii/result-api
    build:
      context: ../apps/result-api
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=development
    volumes:
      - ../apps/result-api:/app
    working_dir: /app
    command: npm run dev
    depends_on:
      - upload-api
  upload-api:
    image: scanii/upload-api
    build:
      context: ../apps/upload-api
      dockerfile: Dockerfile
    ports:
      - 3002:3002
    environment:
      - NODE_ENV=development
    volumes:
      - ../apps/upload-api:/app
    working_dir: /app
    command: npm run dev
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - ../redis-data:/data
  minio:
    image: minio/minio
    ports:
      - 9000:9000
    volumes:
      - ../minio-data:/data
    environment:
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadmin
    command: minio server /data --console-address ":9001"


